services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: envoy
    volumes:
      - ./envoy:/etc/envoy
    ports:
      - "8080:8080"
    depends_on:
      - opa
      - api
    networks:
      - backend

  opa:
    image: openpolicyagent/opa:latest-envoy
    container_name: opa
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-level=debug"
      - "--set=plugins.envoy_ext_authz_grpc.addr=0.0.0.0:9191"
      - "--set=plugins.envoy_ext_authz_grpc.path=envoy/main/allow"
      - "/policies"
    volumes:
      - ./opa/policies:/policies
    networks:
      - backend

  api:
    build: ./backend
    container_name: nest-api
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      PREFIX: api
      SWAGGER_TITLE: rmis
      SWAGGER_DESCRIPTION: Rider Medical Information System API description
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: test
      JWT_SECRET: 4ec518be75bad3784fe4c3b4d8e4d67c8539e91f3be766ecdf6e27cb0e50d4cb
      ACCESS_TOKEN_EXPIRATION: 20m
      REFRESH_TOKEN_EXPIRATION: 7d
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: